name: pc
adopt-info: pc
type: gadget
base: core24
icon: snap/gui/icon.png
license: "CC-BY-SA-4.0 AND GPL-3.0-or-later"
website: https://gnu.org/software/grub
contact: dilyn.corner@tutanota.com
issues: https://github.com/dilyn-corner/pc-gadget/issues
source-code: https://github.com/dilyn-corner/pc-gadget
summary: PC gadget for generic devices
description: |
  This gadget enables generic pc devices to work with Ubuntu Core
confinement: strict
grade: stable

hooks:
  prepare-device:
    plugs: [hardware-observe]
    environment:
      MODEL_APIKEY: "NAS_APIKEY"

# Min version to support shim 15.7
assumes:
  - snapd2.63

parts:
  pc:
    plugin: nil
    stage-snaps: [pc/24/stable]
    stage-packages: [dmidecode]
    override-stage: |
      craftctl default

      # Grab the grub2 package version, hopefully. Probably.
      craftctl set version="$(strings grubx64.efi | grep -i Ubuntu,grub2|cut -d, -f5)"
    stage:
      - boot.csv
      - fb.efi
      - grub.conf
      - grubx64.efi
      - shim.efi.signed
      - usr/sbin/dmidecode
      - usr/share/doc/
