name: Regression Test Builds CI

on:
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:

jobs:
  test_build:
    name: Test build to check for regressions
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: classic
      - name: Build
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: latest/edge
